package view;

import bean.CvsClientes;
import dao.CvsClientesDAO;
import java.text.ParseException;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author user
 */
public class JDlgCvsClientes extends javax.swing.JDialog {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean incluir;
    boolean pesquisando = false;

    public JDlgCvsClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        Util.habilitar(false,
                jTxtCvsNome,
                jTxtCvsEmail,
                jFmtCvsCpf,
                jFmtCvsRg,
                jFmtCvsCep,
                jTxtCvsEstado,
                jTxtCvsEndereco,
                jTxtCidade,
                jTxtCvsBairro,
                jFmtCvsTelefone,
                jTxtCvsNacionalidade,
                jTxtCvsSexo,
                jFmtCvsDataCadastro,
                jFmtCvsDataNascimento,
                jTxtCvsCodigo,
                jBtnCvsConfirmar,
                jBtnCvsCancelar
        );
        // CPF
        try {
            MaskFormatter mascara = new MaskFormatter("###.###.###-##");
            jFmtCvsCpf.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

// Data Nascimento / Cadastro
        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            jFmtCvsDataNascimento.setFormatterFactory(new DefaultFormatterFactory(mascara));
            jFmtCvsDataCadastro.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

// Telefone
        try {
            MaskFormatter mascara = new MaskFormatter("(##) #####-####");
            jFmtCvsTelefone.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

// CEP
        try {
            MaskFormatter mascara = new MaskFormatter("#####-###");
            jFmtCvsCep.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

    }

    public CvsClientes viewBean() {
        CvsClientes cliente = new CvsClientes();

        cliente.setCvsIdCliente(Util.strToInt(jTxtCvsCodigo.getText()));
        cliente.setCvsNome(jTxtCvsNome.getText());
        cliente.setCvsEmail(jTxtCvsEmail.getText());
        cliente.setCvsCidade(jTxtCvsCidade.getText());
        cliente.setCvsRg(jFmtCvsRg.getText());
        cliente.setCvsDataNascimento(Util.strToDate(jFmtCvsDataNascimento.getText()));
        cliente.setCvsTelefone(jFmtCvsTelefone.getText());
        cliente.setCvsEndereco(jTxtCvsEndereco.getText());
        cliente.setCvsSexo(jTxtCvsSexo.getText());
        cliente.setCvsDataCadastro(Util.strToDate(jFmtCvsDataCadastro.getText()));
        cliente.setCvsCpf(jFmtCvsCpf.getText());
        cliente.setCvsEstado(jTxtCvsEstado.getText());
        cliente.setCvsCep(jFmtCvsCep.getText());
        cliente.setCvsBairro(jTxtCvsBairro.getText());
        cliente.setCvsNacionalidade(jTxtCvsNacionalidade.getText());

        return cliente;
    }

    public void beanView(CvsClientes cliente) {
        jTxtCvsCodigo.setText(Util.intToStr(cliente.getCvsIdCliente()));
        jTxtCvsNome.setText(cliente.getCvsNome());
        jTxtCvsEmail.setText(cliente.getCvsEmail());
        jTxtCvsCidade.setText(cliente.getCvsCidade());
        jFmtCvsRg.setText(cliente.getCvsRg());
        jFmtCvsDataNascimento.setText(Util.dateToStr(cliente.getCvsDataNascimento()));
        jFmtCvsTelefone.setText(cliente.getCvsTelefone());
        jTxtCvsEndereco.setText(cliente.getCvsEndereco());
        jTxtCvsSexo.setText(cliente.getCvsSexo());
        jFmtCvsDataCadastro.setText(Util.dateToStr(cliente.getCvsDataCadastro()));
        jFmtCvsCpf.setText(cliente.getCvsCpf());
        jTxtCvsEstado.setText(cliente.getCvsEstado());
        jFmtCvsCep.setText(cliente.getCvsCep());
        jTxtCvsBairro.setText(cliente.getCvsBairro());
        jTxtCvsNacionalidade.setText(cliente.getCvsNacionalidade());
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCvsCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jChbCvsAtivo = new javax.swing.JCheckBox();
        jLblAtivo = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        jLblSexo = new javax.swing.JLabel();
        jLblDatadeNascimento = new javax.swing.JLabel();
        jLblTelefone = new javax.swing.JLabel();
        jLblCpf = new javax.swing.JLabel();
        jLblRg = new javax.swing.JLabel();
        jLblEndereco = new javax.swing.JLabel();
        jLblCidade = new javax.swing.JLabel();
        jLblEstado = new javax.swing.JLabel();
        jLblCep = new javax.swing.JLabel();
        jLblNacionalidade = new javax.swing.JLabel();
        jLblDatadeCadastro = new javax.swing.JLabel();
        jTxtCvsNome = new javax.swing.JTextField();
        jTxtCvsEmail = new javax.swing.JTextField();
        jTxtCvsEndereco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxtCvsEstado = new javax.swing.JTextField();
        jTxtCvsNacionalidade = new javax.swing.JTextField();
        jTxtCvsSexo = new javax.swing.JTextField();
        jBtnCvsCancelar = new javax.swing.JButton();
        jBtnCvsPesquisar = new javax.swing.JButton();
        jBtnCvsIncluir = new javax.swing.JButton();
        jBtnCvsAlterar = new javax.swing.JButton();
        jBtnCvsExcluir = new javax.swing.JButton();
        jBtnCvsConfirmar = new javax.swing.JButton();
        jLblBairro = new javax.swing.JLabel();
        jTxtCvsBairro = new javax.swing.JTextField();
        jFmtCvsDataCadastro = new javax.swing.JFormattedTextField();
        jFmtCvsTelefone = new javax.swing.JFormattedTextField();
        jFmtCvsCep = new javax.swing.JFormattedTextField();
        jFmtCvsDataNascimento = new javax.swing.JFormattedTextField();
        jFmtCvsCpf = new javax.swing.JFormattedTextField();
        jFmtCvsRg = new javax.swing.JFormattedTextField();
        jTxtCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtCvsCodigo = new javax.swing.JTextField();

        jTxtCvsCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsCidadeActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLblAtivo.setText("Ativo");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblNome.setText("Nome");

        jLblEmail.setText("Email");

        jLblSexo.setText("sexo");

        jLblDatadeNascimento.setText("Data De Nascimento");

        jLblTelefone.setText("Telefone");

        jLblCpf.setText("Cpf");

        jLblRg.setText("Rg");

        jLblEndereco.setText("Endereco");

        jLblCidade.setText("Cidade");

        jLblEstado.setText("Estado");

        jLblCep.setText("Cep");

        jLblNacionalidade.setText("Nacionalidade");

        jLblDatadeCadastro.setText("Data de Cadastro");

        jTxtCvsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsNomeActionPerformed(evt);
            }
        });

        jTxtCvsEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsEnderecoActionPerformed(evt);
            }
        });

        jTxtCvsEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsEstadoActionPerformed(evt);
            }
        });

        jTxtCvsNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsNacionalidadeActionPerformed(evt);
            }
        });

        jTxtCvsSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsSexoActionPerformed(evt);
            }
        });

        jBtnCvsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCvsCancelar.setText("Cancelar");
        jBtnCvsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsCancelarActionPerformed(evt);
            }
        });

        jBtnCvsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnCvsPesquisar.setText("Pesquisar");
        jBtnCvsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsPesquisarActionPerformed(evt);
            }
        });

        jBtnCvsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnCvsIncluir.setText("Incluir");
        jBtnCvsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsIncluirActionPerformed(evt);
            }
        });

        jBtnCvsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnCvsAlterar.setText("Alterar");
        jBtnCvsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsAlterarActionPerformed(evt);
            }
        });

        jBtnCvsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnCvsExcluir.setText("Excluir");
        jBtnCvsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsExcluirActionPerformed(evt);
            }
        });

        jBtnCvsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnCvsConfirmar.setText("Confirmar");
        jBtnCvsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsConfirmarActionPerformed(evt);
            }
        });

        jLblBairro.setText("Bairro");

        jFmtCvsDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCvsDataCadastroActionPerformed(evt);
            }
        });

        jFmtCvsTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCvsTelefoneActionPerformed(evt);
            }
        });

        jFmtCvsCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCvsCepActionPerformed(evt);
            }
        });

        jFmtCvsDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCvsDataNascimentoActionPerformed(evt);
            }
        });

        jFmtCvsRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCvsRgActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo");

        jTxtCvsCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtCvsEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLblEndereco))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLblNacionalidade)
                                                    .addComponent(jTxtCvsEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFmtCvsTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtCvsNacionalidade)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLblCidade)
                                            .addComponent(jLblSexo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblBairro)
                                            .addComponent(jTxtCvsBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTxtCvsSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLblRg)
                                .addGap(96, 96, 96)
                                .addComponent(jLblCep))
                            .addComponent(jLabel16)
                            .addComponent(jLblNome)
                            .addComponent(jLblEmail)
                            .addComponent(jLblCpf)
                            .addComponent(jLblEstado)
                            .addComponent(jLblTelefone)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFmtCvsCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtCvsRg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtCvsCep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtCvsEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                                .addComponent(jTxtCvsNome, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFmtCvsDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtCvsDataNascimento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblDatadeCadastro)
                                .addGap(25, 25, 25)
                                .addComponent(jLblDatadeNascimento)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtCvsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnCvsIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCvsAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCvsExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCvsConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCvsCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCvsPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCvsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCvsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCpf)
                    .addComponent(jLblRg)
                    .addComponent(jLblCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCvsCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCvsRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCvsCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEstado)
                    .addComponent(jLblEndereco)
                    .addComponent(jLblCidade)
                    .addComponent(jLblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCvsEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCvsEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCvsBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefone)
                    .addComponent(jLblNacionalidade)
                    .addComponent(jLblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCvsTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCvsNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCvsSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDatadeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDatadeNascimento)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCvsDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCvsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCvsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCvsIncluir)
                    .addComponent(jBtnCvsAlterar)
                    .addComponent(jBtnCvsExcluir)
                    .addComponent(jBtnCvsConfirmar)
                    .addComponent(jBtnCvsCancelar)
                    .addComponent(jBtnCvsPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCvsEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsEnderecoActionPerformed

    private void jTxtCvsEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsEstadoActionPerformed

    private void jBtnCvsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsIncluirActionPerformed
        Util.habilitar(true, jTxtCvsNome, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsRg, jFmtCvsCep, jTxtCvsEstado, jTxtCvsEndereco, jTxtCidade, jTxtCvsBairro, jFmtCvsTelefone, jTxtCvsNacionalidade, jTxtCvsSexo, jFmtCvsDataCadastro, jFmtCvsDataNascimento, jTxtCvsCodigo, jBtnCvsConfirmar, jBtnCvsCancelar);
        Util.habilitar(false, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);
        Util.limpar(jTxtCvsCodigo, jTxtCvsNome, jTxtCvsEmail);
        jTxtCvsCodigo.grabFocus();
        incluir = true;
    }//GEN-LAST:event_jBtnCvsIncluirActionPerformed

    private void jTxtCvsNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsNacionalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsNacionalidadeActionPerformed

    private void jBtnCvsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCvsNome, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsRg, jFmtCvsCep, jTxtCvsEstado, jTxtCvsEndereco, jTxtCidade, jTxtCvsBairro, jFmtCvsTelefone, jTxtCvsNacionalidade, jTxtCvsSexo, jFmtCvsDataCadastro, jFmtCvsDataNascimento, jTxtCvsCodigo, jBtnCvsConfirmar, jBtnCvsCancelar);
        Util.habilitar(true, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);
        Util.limpar(jTxtCvsNome, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsRg, jFmtCvsCep, jTxtCvsEstado, jTxtCvsEndereco, jTxtCidade, jTxtCvsBairro, jFmtCvsTelefone, jTxtCvsNacionalidade, jTxtCvsSexo, jFmtCvsDataCadastro, jFmtCvsDataNascimento, jTxtCvsCodigo);
    }//GEN-LAST:event_jBtnCvsCancelarActionPerformed

    private void jBtnCvsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCvsNome, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsRg, jFmtCvsCep, jTxtCvsEstado, jTxtCvsEndereco, jTxtCidade, jTxtCvsBairro, jFmtCvsTelefone, jTxtCvsNacionalidade, jTxtCvsSexo, jFmtCvsDataCadastro, jFmtCvsDataNascimento, jTxtCvsCodigo, jBtnCvsConfirmar, jBtnCvsCancelar);
        Util.habilitar(true, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);
        CvsClientesDAO cvsClientesDAO = new CvsClientesDAO();
        if (incluir == true) {
            cvsClientesDAO.insert(viewBean());
        } else {
            cvsClientesDAO.update(viewBean());
        }
        Util.limpar(jTxtCvsNome, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsRg, jFmtCvsCep, jTxtCvsEstado, jTxtCvsEndereco, jTxtCidade, jTxtCvsBairro, jFmtCvsTelefone, jTxtCvsNacionalidade, jTxtCvsSexo, jFmtCvsDataCadastro, jFmtCvsDataNascimento, jTxtCvsCodigo);
    }//GEN-LAST:event_jBtnCvsConfirmarActionPerformed

    private void jTxtCvsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsNomeActionPerformed

    private void jBtnCvsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsRg, jFmtCvsCep, jTxtCvsEstado, jTxtCvsEndereco, jTxtCidade, jTxtCvsBairro, jFmtCvsTelefone, jTxtCvsNacionalidade, jTxtCvsSexo, jFmtCvsDataCadastro, jFmtCvsDataNascimento, jTxtCvsCodigo, jBtnCvsConfirmar, jBtnCvsCancelar);
        Util.habilitar(false, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);
        incluir = false;
        jTxtCvsNome.grabFocus();
    }//GEN-LAST:event_jBtnCvsAlterarActionPerformed

    private void jBtnCvsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsExcluirActionPerformed
        // TODO add your handling code here:
        if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar primeiro");
        } else {
            if (Util.perguntar("Você deseja excluir?") == true) {
                CvsClientesDAO cvsClientesDAO = new CvsClientesDAO();
                cvsClientesDAO.delete(viewBean());
            }
            Util.limpar(jTxtCvsNome, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsRg, jFmtCvsCep, jTxtCvsEstado, jTxtCvsEndereco, jTxtCidade, jTxtCvsBairro, jFmtCvsTelefone, jTxtCvsNacionalidade, jTxtCvsSexo, jFmtCvsDataCadastro, jFmtCvsDataNascimento, jTxtCvsCodigo);
        }
    }//GEN-LAST:event_jBtnCvsExcluirActionPerformed

    private void jBtnCvsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgCvsClientesPesquisar jDlgCvsClientesPesquisar = new JDlgCvsClientesPesquisar(null, true);
        jDlgCvsClientesPesquisar.setTelaPai(this);
        jDlgCvsClientesPesquisar.setVisible(true);
        pesquisando = true;
    }//GEN-LAST:event_jBtnCvsPesquisarActionPerformed

    private void jFmtCvsTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCvsTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCvsTelefoneActionPerformed

    private void jFmtCvsDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCvsDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCvsDataNascimentoActionPerformed

    private void jFmtCvsRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCvsRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCvsRgActionPerformed

    private void jTxtCvsCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsCidadeActionPerformed

    private void jFmtCvsCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCvsCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCvsCepActionPerformed

    private void jTxtCvsSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsSexoActionPerformed

    private void jFmtCvsDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCvsDataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCvsDataCadastroActionPerformed

    private void jTxtCvsCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCvsClientes dialog = new JDlgCvsClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCvsAlterar;
    private javax.swing.JButton jBtnCvsCancelar;
    private javax.swing.JButton jBtnCvsConfirmar;
    private javax.swing.JButton jBtnCvsExcluir;
    private javax.swing.JButton jBtnCvsIncluir;
    private javax.swing.JButton jBtnCvsPesquisar;
    private javax.swing.JCheckBox jChbCvsAtivo;
    private javax.swing.JFormattedTextField jFmtCvsCep;
    private javax.swing.JFormattedTextField jFmtCvsCpf;
    private javax.swing.JFormattedTextField jFmtCvsDataCadastro;
    private javax.swing.JFormattedTextField jFmtCvsDataNascimento;
    private javax.swing.JFormattedTextField jFmtCvsRg;
    private javax.swing.JFormattedTextField jFmtCvsTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblAtivo;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCep;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblCpf;
    private javax.swing.JLabel jLblDatadeCadastro;
    private javax.swing.JLabel jLblDatadeNascimento;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEndereco;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JLabel jLblNacionalidade;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblRg;
    private javax.swing.JLabel jLblSexo;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtCvsBairro;
    private javax.swing.JTextField jTxtCvsCidade;
    private javax.swing.JTextField jTxtCvsCodigo;
    private javax.swing.JTextField jTxtCvsEmail;
    private javax.swing.JTextField jTxtCvsEndereco;
    private javax.swing.JTextField jTxtCvsEstado;
    private javax.swing.JTextField jTxtCvsNacionalidade;
    private javax.swing.JTextField jTxtCvsNome;
    private javax.swing.JTextField jTxtCvsSexo;
    // End of variables declaration//GEN-END:variables
}
