package view;

import bean.CvsJoias;
import dao.CvsJoiasDAO;
import tools.Util;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author amand
 */
public class JDlgCvsJoias extends javax.swing.JDialog {

    /**
     * Creates new form JDlgJoias
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    boolean pesquisando = false;
    private boolean incluir;

    public JDlgCvsJoias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Jóias");
        setLocationRelativeTo(null);
        habilitar(false);
    }

    public CvsJoias viewBean() {
        CvsJoias joia = new CvsJoias();

        joia.setCvsIdJoias(Util.strToInt(jTxtCvsCodigo.getText()));
        joia.setCvsNome(jTxtCvsNome.getText());
        joia.setCvsTipo(jTxtCvsTipo.getText());
        joia.setCvsMaterial(jFmtCvsMaterial.getText());
        joia.setCvsDescricao(jTxtDescricao.getText());
        joia.setCvsPeso(Util.strToDouble(jTxtCvsPeso.getText()));
        joia.setCvsPreco(Util.strToDouble(jTxtPreco.getText()));

        return joia;
    }

    public void beanView(CvsJoias joia) {
        jTxtCvsCodigo.setText(Util.intToStr(joia.getCvsIdJoias()));
        jTxtCvsNome.setText(joia.getCvsNome());
        jTxtCvsTipo.setText(joia.getCvsTipo());
        jFmtCvsMaterial.setText(joia.getCvsMaterial());
        jTxtDescricao.setText(joia.getCvsDescricao());
        jTxtCvsPeso.setText(Util.doubleToStr(joia.getCvsPeso()));
        jTxtPreco.setText(Util.doubleToStr(joia.getCvsPreco()));
    }

    public void habilitar(boolean status) {
        if (status) {
            Util.habilitar(true, jTxtCvsNome, jTxtCvsCodigo, jTxtCvsTipo, jFmtCvsMaterial, jTxtDescricao, jTxtCvsPeso, jTxtPreco, jBtnCvsConfirmar, jBtnCvsCancelar);
            Util.habilitar(false, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);
        } else {
            Util.habilitar(false, jTxtCvsNome, jTxtCvsCodigo, jTxtCvsTipo, jFmtCvsMaterial, jTxtDescricao, jTxtCvsPeso, jTxtPreco, jBtnCvsConfirmar, jBtnCvsCancelar);
            Util.habilitar(true, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);
        }
    }

    public void limparCampos() {
        Util.limpar(jTxtCvsNome, jTxtCvsCodigo, jTxtCvsTipo, jFmtCvsMaterial, jTxtDescricao, jTxtCvsPeso, jTxtPreco);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtCvsNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtCvsCodigo = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtCvsTipo = new javax.swing.JTextField();
        jFmtCvsMaterial = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jBtnCvsIncluir = new javax.swing.JButton();
        jBtnCvsAlterar = new javax.swing.JButton();
        jBtnCvsExcluir = new javax.swing.JButton();
        jBtnCvsConfirmar = new javax.swing.JButton();
        jBtnCvsCancelar = new javax.swing.JButton();
        jBtnCvsPesquisar = new javax.swing.JButton();
        jTxtCvsPeso = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtPreco = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtDescricao = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jTxtCvsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        jLabel3.setText("Tipo");

        jLabel5.setText("Material");

        jBtnCvsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnCvsIncluir.setText("Incluir");
        jBtnCvsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsIncluirActionPerformed(evt);
            }
        });

        jBtnCvsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnCvsAlterar.setText("Alterar");
        jBtnCvsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsAlterarActionPerformed(evt);
            }
        });

        jBtnCvsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnCvsExcluir.setText("Excluir");
        jBtnCvsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsExcluirActionPerformed(evt);
            }
        });

        jBtnCvsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnCvsConfirmar.setText("Confirmar");
        jBtnCvsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsConfirmarActionPerformed(evt);
            }
        });

        jBtnCvsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCvsCancelar.setText("Cancelar");
        jBtnCvsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsCancelarActionPerformed(evt);
            }
        });

        jBtnCvsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnCvsPesquisar.setText("Pesquisar");
        jBtnCvsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsPesquisarActionPerformed(evt);
            }
        });

        jLabel6.setText("Peso");

        jLabel7.setText("Preço");

        jLabel8.setText("Descrição");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtCvsNome, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jTxtCvsCodigo)
                    .addComponent(jTxtCvsTipo)
                    .addComponent(jFmtCvsMaterial))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnCvsIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCvsPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCvsPeso)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(152, 152, 152))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPreco)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(152, 152, 152))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(152, 152, 152)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCvsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCvsPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCvsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCvsTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCvsMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCvsIncluir)
                    .addComponent(jBtnCvsAlterar)
                    .addComponent(jBtnCvsExcluir)
                    .addComponent(jBtnCvsConfirmar)
                    .addComponent(jBtnCvsCancelar)
                    .addComponent(jBtnCvsPesquisar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCvsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsNomeActionPerformed

    private void jBtnCvsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        CvsJoiasDAO cvsJoiasDAO = new CvsJoiasDAO();
        if (incluir == true) {
            cvsJoiasDAO.insert(viewBean());
        } else {
            cvsJoiasDAO.update(viewBean());
        }
        limparCampos();
    }//GEN-LAST:event_jBtnCvsConfirmarActionPerformed

    private void jBtnCvsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsExcluirActionPerformed
        // TODO add your handling code here:
        if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar primeiro");
        } else {
            if (Util.perguntar("Você deseja excluir?") == true) {
                CvsJoiasDAO cvsJoiasDAO = new CvsJoiasDAO();
                cvsJoiasDAO.delete(viewBean());
            }
            limparCampos();
        }
    }//GEN-LAST:event_jBtnCvsExcluirActionPerformed

    private void jBtnCvsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtCvsNome, jTxtCvsTipo, jFmtCvsMaterial, jBtnCvsConfirmar, jBtnCvsCancelar, jTxtCvsPeso, jTxtDescricao, jTxtPreco);
        Util.habilitar(false, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);
        incluir = false;
        jTxtCvsNome.grabFocus();
    }//GEN-LAST:event_jBtnCvsAlterarActionPerformed

    private void jBtnCvsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limparCampos();
        incluir = true;
    }//GEN-LAST:event_jBtnCvsIncluirActionPerformed

    private void jBtnCvsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        limparCampos();
    }//GEN-LAST:event_jBtnCvsCancelarActionPerformed

    private void jBtnCvsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgCvsJoiasPesquisar jDlgCvsJoiasPesquisar = new JDlgCvsJoiasPesquisar(null, true);
        jDlgCvsJoiasPesquisar.setTelaPai(this);
        jDlgCvsJoiasPesquisar.setVisible(true);
        pesquisando = true;
    }//GEN-LAST:event_jBtnCvsPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsJoias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsJoias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsJoias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsJoias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCvsJoias dialog = new JDlgCvsJoias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCvsAlterar;
    private javax.swing.JButton jBtnCvsCancelar;
    private javax.swing.JButton jBtnCvsConfirmar;
    private javax.swing.JButton jBtnCvsExcluir;
    private javax.swing.JButton jBtnCvsIncluir;
    private javax.swing.JButton jBtnCvsPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFmtCvsMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField jTxtCvsCodigo;
    private javax.swing.JTextField jTxtCvsNome;
    private javax.swing.JFormattedTextField jTxtCvsPeso;
    private javax.swing.JTextField jTxtCvsTipo;
    private javax.swing.JFormattedTextField jTxtDescricao;
    private javax.swing.JFormattedTextField jTxtPreco;
    // End of variables declaration//GEN-END:variables
}
