/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CvsVendasDAO;
import bean.CvsClientes;
import bean.CvsFuncionarios;
import bean.CvsVendas;
import bean.CvsVendasjoias;
import tools.Util;
import java.util.List;
import dao.CvsClientesDAO;
import dao.CvsFuncionarioDAO;
import dao.CvsVendasJoiasDAO;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author u1845853
 */
public class JDlgCvsVendas extends javax.swing.JDialog {

    ControllerCvsVendasJoias controllerCvsVendasJoias;
    private boolean incluir;
    boolean pesquisando = false;

    /**
     * Creates new form JDlgCvsVendas
     */
    public JDlgCvsVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        habilitar(false);

        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            jFmtCvsData.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

        CvsClientesDAO clientesDAO = new CvsClientesDAO();
        List listaClientes = (List) clientesDAO.listAll();
        for (int i = 0; i < listaClientes.size(); i++) {
            jCboCvsClientes.addItem((CvsClientes) listaClientes.get(i));
        }

        CvsFuncionarioDAO cvsFuncionarioDAO = new CvsFuncionarioDAO();
        List listaFuncionarios = (List) cvsFuncionarioDAO.listAll();
        for (int i = 0; i < listaFuncionarios.size(); i++) {
            jCboCvsVendedor.addItem((CvsFuncionarios) listaFuncionarios.get(i));
        }

        controllerCvsVendasJoias = new ControllerCvsVendasJoias();
        controllerCvsVendasJoias.setList(new ArrayList());
        jTblVendaJoias.setModel(controllerCvsVendasJoias);

    }

    public CvsVendas viewBean() {
        CvsVendas vendas = new CvsVendas();
        vendas.setCvsIdVenda(Util.strToInt(jTxtCvsCodigo.getText()));
        vendas.setCvsFuncionarios((CvsFuncionarios) jCboCvsVendedor.getSelectedItem());
        vendas.setCvsClientes((CvsClientes) jCboCvsClientes.getSelectedItem());
        vendas.setCvsDataVenda(Util.strToDate(jFmtCvsData.getText()));
        vendas.setCvsTotal(Util.strToDouble(jTxtCvsTotal.getText()));
        return vendas;
    }

    public void beanView(CvsVendas vendas) {
        jTxtCvsCodigo.setText(Util.intToStr(vendas.getCvsIdVenda()));
        jCboCvsVendedor.setSelectedItem(vendas.getCvsClientes());
        jCboCvsClientes.setSelectedItem(vendas.getCvsFuncionarios());
        jFmtCvsData.setText(Util.dateToStr(vendas.getCvsDataVenda()));
        jTxtCvsTotal.setText(Util.doubleToStr(vendas.getCvsTotal()));

        CvsVendasJoiasDAO cvsVendasJoiasDAO = new CvsVendasJoiasDAO();
        List listaVendaJoias = (List) cvsVendasJoiasDAO.listJoias(vendas);
        controllerCvsVendasJoias.setList(listaVendaJoias);
    }

    public void habilitar(boolean status) {
        if (status) {
            Util.habilitar(true, jTxtCvsCodigo, jFmtCvsData, jCboCvsClientes,
                    jCboCvsVendedor, jTxtCvsTotal, jBtnCVsConfirmar, jBtnCvsCancelar,
                    jTblVendaJoias, jBtnCvsIncluirProd, jBtnCvsAlterarProd, jBtnCvsExcluirProd);
            Util.habilitar(false, jBtnCvsIncluir, jBtnCvsAlterar, jBtnCvsExcluir,
                    jBtnCvsPesquisar);
        } else {
            Util.habilitar(false, jTxtCvsCodigo, jFmtCvsData, jCboCvsClientes,
                    jCboCvsVendedor, jTxtCvsTotal, jBtnCVsConfirmar, jBtnCvsCancelar,
                    jTblVendaJoias, jBtnCvsIncluirProd, jBtnCvsAlterarProd, jBtnCvsExcluirProd);
            Util.habilitar(true, jBtnCvsIncluir, jBtnCvsAlterar, jBtnCvsExcluir,
                    jBtnCvsPesquisar);
        }
    }

    public void limparCampos() {
        Util.limpar(jTxtCvsCodigo, jFmtCvsData, jCboCvsClientes, jCboCvsVendedor,
                jTxtCvsTotal);
        controllerCvsVendasJoias.setList(new ArrayList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCvsCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFmtCvsData = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jCboCvsVendedor = new javax.swing.JComboBox<CvsFuncionarios>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtCvsTotal = new javax.swing.JTextField();
        jBtnCvsIncluir = new javax.swing.JButton();
        jBtnCvsAlterar = new javax.swing.JButton();
        jBtnCvsExcluir = new javax.swing.JButton();
        jBtnCVsConfirmar = new javax.swing.JButton();
        jBtnCvsCancelar = new javax.swing.JButton();
        jBtnCvsPesquisar = new javax.swing.JButton();
        jBtnCvsIncluirProd = new javax.swing.JButton();
        jBtnCvsAlterarProd = new javax.swing.JButton();
        jBtnCvsExcluirProd = new javax.swing.JButton();
        jCboCvsClientes = new javax.swing.JComboBox<CvsClientes>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblVendaJoias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("Data");

        jFmtCvsData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCvsDataActionPerformed(evt);
            }
        });

        jLabel3.setText("Clientes");

        jCboCvsVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboCvsVendedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Vendedor");

        jLabel5.setText("Total");

        jBtnCvsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnCvsIncluir.setText("Incluir");
        jBtnCvsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsIncluirActionPerformed(evt);
            }
        });

        jBtnCvsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnCvsAlterar.setText("Alterar");
        jBtnCvsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsAlterarActionPerformed(evt);
            }
        });

        jBtnCvsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnCvsExcluir.setText("Excluir");
        jBtnCvsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsExcluirActionPerformed(evt);
            }
        });

        jBtnCVsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnCVsConfirmar.setText("Confirmar");
        jBtnCVsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCVsConfirmarActionPerformed(evt);
            }
        });

        jBtnCvsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCvsCancelar.setText("Cancelar");
        jBtnCvsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsCancelarActionPerformed(evt);
            }
        });

        jBtnCvsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnCvsPesquisar.setText("Pesquisar");
        jBtnCvsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsPesquisarActionPerformed(evt);
            }
        });

        jBtnCvsIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnCvsIncluirProd.setToolTipText("");
        jBtnCvsIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsIncluirProdActionPerformed(evt);
            }
        });

        jBtnCvsAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnCvsAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsAlterarProdActionPerformed(evt);
            }
        });

        jBtnCvsExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnCvsExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsExcluirProdActionPerformed(evt);
            }
        });

        jCboCvsClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboCvsClientesActionPerformed(evt);
            }
        });

        jTblVendaJoias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblVendaJoias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCvsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtCvsData, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jCboCvsClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCboCvsVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxtCvsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnCvsIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCVsConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCvsAlterarProd)
                    .addComponent(jBtnCvsIncluirProd)
                    .addComponent(jBtnCvsExcluirProd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtCvsData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboCvsClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCvsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtCvsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboCvsVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnCvsIncluirProd)
                        .addGap(7, 7, 7)
                        .addComponent(jBtnCvsAlterarProd)
                        .addGap(4, 4, 4)
                        .addComponent(jBtnCvsExcluirProd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCvsIncluir)
                    .addComponent(jBtnCvsAlterar)
                    .addComponent(jBtnCvsExcluir)
                    .addComponent(jBtnCvsCancelar)
                    .addComponent(jBtnCvsPesquisar)
                    .addComponent(jBtnCVsConfirmar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCvsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limparCampos();
        jTxtCvsCodigo.grabFocus();
        incluir = true;
    }//GEN-LAST:event_jBtnCvsIncluirActionPerformed

    private void jBtnCvsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jFmtCvsData, jCboCvsClientes, jCboCvsVendedor, jTxtCvsTotal, jTblVendaJoias, jBtnCvsIncluirProd, jBtnCvsAlterarProd, jBtnCvsExcluirProd, jBtnCVsConfirmar, jBtnCvsCancelar);
        Util.habilitar(false, jBtnCvsIncluir, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar);
        jFmtCvsData.grabFocus();
        incluir = false;
    }//GEN-LAST:event_jBtnCvsAlterarActionPerformed

    private void jBtnCvsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsExcluirActionPerformed
        //TODO add your handling code here:
        if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar primeiro");
        } else {
            if (Util.perguntar("Deseja Excluir?") == true) {
                CvsVendasDAO vendasDAO = new CvsVendasDAO();
                vendasDAO.delete(viewBean());
                limparCampos();
            }
        }
    }//GEN-LAST:event_jBtnCvsExcluirActionPerformed

    private void jBtnCVsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCVsConfirmarActionPerformed
        // TODO add your handling code here:
        CvsVendasDAO vendasDAO = new CvsVendasDAO();
        CvsVendasJoiasDAO cvsVendasJoiasDAO = new CvsVendasJoiasDAO();

        if (incluir == true) {
            vendasDAO.insert(viewBean());
            for (int ind = 0; ind < jTblVendaJoias.getRowCount(); ind++) {
                CvsVendasjoias cvsVendasJoias = (CvsVendasjoias) controllerCvsVendasJoias.getBean(ind);
                cvsVendasJoias.setCvsVendas(viewBean());
                cvsVendasJoiasDAO.insert(cvsVendasJoias);
            }
        } else {
            vendasDAO.update(viewBean());
        }
        habilitar(false);
        limparCampos();
    }//GEN-LAST:event_jBtnCVsConfirmarActionPerformed

    private void jBtnCvsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        limparCampos();
    }//GEN-LAST:event_jBtnCvsCancelarActionPerformed

    private void jBtnCvsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgCvsVendasPesquisar JDlgCvsVendas = new JDlgCvsVendasPesquisar(null, true);
        JDlgCvsVendas.setTelaPai(this);
        JDlgCvsVendas.setVisible(true);
    }//GEN-LAST:event_jBtnCvsPesquisarActionPerformed

    private void jBtnCvsExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsExcluirProdActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja Excluir?") == true) {
            int rowIndex = jTblVendaJoias.getSelectedRow();
            controllerCvsVendasJoias.removeBean(controllerCvsVendasJoias.getBean(rowIndex));
        }

    }//GEN-LAST:event_jBtnCvsExcluirProdActionPerformed

    private void jBtnCvsAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsAlterarProdActionPerformed
        // TODO add your handling code here:
        JDlgCvsVendasJoias jDlgCvsVendasJoias = new JDlgCvsVendasJoias(null, true);
        jDlgCvsVendasJoias.setTelaPai(this);
        jDlgCvsVendasJoias.setVisible(true);
    }//GEN-LAST:event_jBtnCvsAlterarProdActionPerformed

    private void jBtnCvsIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsIncluirProdActionPerformed
        // TODO add your handling code here:
        JDlgCvsVendasJoias jDlgCvsVendasJoias = new JDlgCvsVendasJoias(null, true);
        jDlgCvsVendasJoias.setTelaPai(this);
        jDlgCvsVendasJoias.setVisible(true);

    }//GEN-LAST:event_jBtnCvsIncluirProdActionPerformed

    private void jCboCvsClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboCvsClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboCvsClientesActionPerformed

    private void jFmtCvsDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCvsDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCvsDataActionPerformed

    private void jCboCvsVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboCvsVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboCvsVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCvsVendas dialog = new JDlgCvsVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCVsConfirmar;
    private javax.swing.JButton jBtnCvsAlterar;
    private javax.swing.JButton jBtnCvsAlterarProd;
    private javax.swing.JButton jBtnCvsCancelar;
    private javax.swing.JButton jBtnCvsExcluir;
    private javax.swing.JButton jBtnCvsExcluirProd;
    private javax.swing.JButton jBtnCvsIncluir;
    private javax.swing.JButton jBtnCvsIncluirProd;
    private javax.swing.JButton jBtnCvsPesquisar;
    private javax.swing.JComboBox<CvsClientes> jCboCvsClientes;
    private javax.swing.JComboBox<CvsFuncionarios> jCboCvsVendedor;
    private javax.swing.JFormattedTextField jFmtCvsData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblVendaJoias;
    private javax.swing.JTextField jTxtCvsCodigo;
    private javax.swing.JTextField jTxtCvsTotal;
    // End of variables declaration//GEN-END:variables
}
