package view;

import bean.CvsUsuario;
import dao.CvsUsuarioDAO;
import java.text.ParseException;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
//package view;
/**
 *
 * @author marcos
 */
public class JDlgCvsUsuario extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuario
     */
    private boolean incluir;
    boolean pesquisando = false;

    public JDlgCvsUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        Util.habilitar(false,
                jTxtCvsCodigo,
                jTxtCvsNome,
                jTxtCvsApelido,
                jFmtCvsCpf,
                jFmtCvsDataNasc,
                jPwdCvsSenha,
                jChbCvsAtivo,
                jBtnCvsConfirmar,
                jBtnCvsCancelar
        );
        try {
            MaskFormatter mascara = new MaskFormatter("###.###.###-##");
            jFmtCvsCpf.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            jFmtCvsDataNasc.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }

    public CvsUsuario viewBean() {
        CvsUsuario cvsUsuario = new CvsUsuario();
        cvsUsuario.setCvsIdUsuario(Util.strToInt(jTxtCvsCodigo.getText()));
        cvsUsuario.setCvsNome(jTxtCvsNome.getText());
        cvsUsuario.setCvsApelido(jTxtCvsApelido.getText());
        cvsUsuario.setCvsSenha(jFmtCvsCpf.getText());
        cvsUsuario.setCvsDataNascimento(Util.strToDate(jFmtCvsDataNasc.getText()));
        cvsUsuario.setCvsSenha(jPwdCvsSenha.getText());
        if (jChbCvsAtivo.isSelected()) {
            cvsUsuario.setCvsAtivo(1);
        } else {
            cvsUsuario.setCvsAtivo(0);
        }
        cvsUsuario.setCvsCpf(jFmtCvsCpf.getText());
        return cvsUsuario;
    }

    public void beanView(CvsUsuario cvsUsuario) {
        jTxtCvsCodigo.setText(Util.intToStr(cvsUsuario.getCvsIdUsuario()));
        jTxtCvsNome.setText(cvsUsuario.getCvsNome());
        jTxtCvsApelido.setText(cvsUsuario.getCvsApelido());
        jFmtCvsCpf.setText(cvsUsuario.getCvsCpf());
        jFmtCvsDataNasc.setText(Util.dateToStr(cvsUsuario.getCvsDataNascimento()));
        jPwdCvsSenha.setText(cvsUsuario.getCvsSenha());
        if (cvsUsuario.getCvsAtivo() == 1) {
            jChbCvsAtivo.setSelected(true);
        } else {
            jChbCvsAtivo.setSelected(false);
        }
    }

    public void habilitar(boolean status) {
        if (status) {
            Util.habilitar(true, jTxtCvsCodigo, jTxtCvsNome, jTxtCvsApelido, jFmtCvsCpf, jFmtCvsDataNasc, jPwdCvsSenha, jChbCvsAtivo, jBtnCvsConfirmar, jBtnCvsCancelar);
            Util.habilitar(false, jBtnCvsIncluir, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar);
        } else {
            Util.habilitar(false, jTxtCvsCodigo, jTxtCvsNome, jTxtCvsApelido, jFmtCvsCpf, jFmtCvsDataNasc, jPwdCvsSenha, jChbCvsAtivo, jBtnCvsConfirmar, jBtnCvsCancelar);
            Util.habilitar(true, jBtnCvsIncluir, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar);
        }
    }

    public void limparCampos() {
        Util.limpar(jTxtCvsCodigo, jTxtCvsNome, jTxtCvsApelido, jFmtCvsCpf, jFmtCvsDataNasc, jPwdCvsSenha, jChbCvsAtivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCvsCodigo = new javax.swing.JLabel();
        jTxtCvsCodigo = new javax.swing.JTextField();
        jLblCvsNome = new javax.swing.JLabel();
        jLblCvsApelido = new javax.swing.JLabel();
        jTxtCvsApelido = new javax.swing.JTextField();
        jLblCvsCpf = new javax.swing.JLabel();
        jLblCvsDataDeNascimento = new javax.swing.JLabel();
        jLblCvsSenha = new javax.swing.JLabel();
        jTxtCvsNome = new javax.swing.JTextField();
        jLblCvsAtivo = new javax.swing.JLabel();
        jChbCvsAtivo = new javax.swing.JCheckBox();
        jBtnCvsCancelar = new javax.swing.JButton();
        jBtnCvsPesquisar = new javax.swing.JButton();
        jBtnCvsIncluir = new javax.swing.JButton();
        jBtnCvsAlterar = new javax.swing.JButton();
        jBtnCvsExcluir = new javax.swing.JButton();
        jBtnCvsConfirmar = new javax.swing.JButton();
        jFmtCvsCpf = new javax.swing.JFormattedTextField();
        jFmtCvsDataNasc = new javax.swing.JFormattedTextField();
        jPwdCvsSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCvsCodigo.setText("Codigo");

        jTxtCvsCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsCodigoActionPerformed(evt);
            }
        });

        jLblCvsNome.setText("Nome:");

        jLblCvsApelido.setText("Apelido:");

        jTxtCvsApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsApelidoActionPerformed(evt);
            }
        });

        jLblCvsCpf.setText("Cpf:");

        jLblCvsDataDeNascimento.setText("Data De Nascimento");

        jLblCvsSenha.setText("Senha");

        jTxtCvsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsNomeActionPerformed(evt);
            }
        });

        jLblCvsAtivo.setText("Ativo:");

        jBtnCvsCancelar.setText("Cancelar");
        jBtnCvsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsCancelarActionPerformed(evt);
            }
        });

        jBtnCvsPesquisar.setText("Pesquisar");
        jBtnCvsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsPesquisarActionPerformed(evt);
            }
        });

        jBtnCvsIncluir.setText("Incluir");
        jBtnCvsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsIncluirActionPerformed(evt);
            }
        });

        jBtnCvsAlterar.setText("Alterar");
        jBtnCvsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsAlterarActionPerformed(evt);
            }
        });

        jBtnCvsExcluir.setText("Excluir");
        jBtnCvsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsExcluirActionPerformed(evt);
            }
        });

        jBtnCvsConfirmar.setText("Confirmar");
        jBtnCvsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtCvsNome)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCvsNome)
                            .addComponent(jLblCvsCodigo)
                            .addComponent(jTxtCvsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnCvsIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCvsAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCvsExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCvsConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCvsCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCvsPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblCvsCpf)
                                .addGap(316, 316, 316)
                                .addComponent(jLblCvsDataDeNascimento)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblCvsApelido)
                                .addComponent(jTxtCvsApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblCvsSenha)
                                        .addComponent(jPwdCvsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jChbCvsAtivo))
                                        .addComponent(jLblCvsAtivo)))
                                .addComponent(jFmtCvsCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jFmtCvsDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCvsCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCvsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCvsNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCvsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblCvsApelido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCvsApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCvsCpf)
                    .addComponent(jLblCvsDataDeNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCvsCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCvsDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCvsSenha)
                    .addComponent(jLblCvsAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jChbCvsAtivo)
                    .addComponent(jPwdCvsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCvsIncluir)
                    .addComponent(jBtnCvsAlterar)
                    .addComponent(jBtnCvsExcluir)
                    .addComponent(jBtnCvsConfirmar)
                    .addComponent(jBtnCvsCancelar)
                    .addComponent(jBtnCvsPesquisar))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCvsCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsCodigoActionPerformed

    private void jTxtCvsApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsApelidoActionPerformed

    private void jBtnCvsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limparCampos();
        jTxtCvsCodigo.grabFocus();
        incluir = true;
    }//GEN-LAST:event_jBtnCvsIncluirActionPerformed

    private void jTxtCvsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsNomeActionPerformed

    private void jBtnCvsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsConfirmarActionPerformed
        // TODO add your  handling code here:

        CvsUsuarioDAO cvsUsuariosDAO = new CvsUsuarioDAO();
        if (incluir == true) {
            cvsUsuariosDAO.insert(viewBean());
        } else {
            cvsUsuariosDAO.update(viewBean());
        }
        limparCampos();
        habilitar(false);
    }//GEN-LAST:event_jBtnCvsConfirmarActionPerformed

    private void jBtnCvsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        limparCampos();
    }//GEN-LAST:event_jBtnCvsCancelarActionPerformed

    private void jBtnCvsExcluirActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
        if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar primeiro");
        } else {
            if (Util.perguntar("Você deseja excluir?") == true) {
                CvsUsuarioDAO cvsUsuariosDAO = new CvsUsuarioDAO();
                cvsUsuariosDAO.delete(viewBean());
            }
            limparCampos();
        }
    }

         private void jBtnCvsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsAlterarActionPerformed
             // TODO add your handling code here:
             Util.habilitar(true, jTxtCvsNome, jTxtCvsApelido, jFmtCvsCpf, jFmtCvsDataNasc, jPwdCvsSenha, jChbCvsAtivo, jBtnCvsConfirmar, jBtnCvsCancelar);
             Util.habilitar(false, jBtnCvsIncluir, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar);
             incluir = false;
             jTxtCvsNome.grabFocus();
    }//GEN-LAST:event_jBtnCvsAlterarActionPerformed

    private void jBtnCvsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgCvsUsuarioPesquisar jDlgCvsUsuarioPesquisar = new JDlgCvsUsuarioPesquisar(null, true);
        jDlgCvsUsuarioPesquisar.setTelaPai(this);
        jDlgCvsUsuarioPesquisar.setVisible(true);
        pesquisando = true;
    }//GEN-LAST:event_jBtnCvsPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCvsUsuario dialog = new JDlgCvsUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCvsAlterar;
    private javax.swing.JButton jBtnCvsCancelar;
    private javax.swing.JButton jBtnCvsConfirmar;
    private javax.swing.JButton jBtnCvsExcluir;
    private javax.swing.JButton jBtnCvsIncluir;
    private javax.swing.JButton jBtnCvsPesquisar;
    private javax.swing.JCheckBox jChbCvsAtivo;
    private javax.swing.JFormattedTextField jFmtCvsCpf;
    private javax.swing.JFormattedTextField jFmtCvsDataNasc;
    private javax.swing.JLabel jLblCvsApelido;
    private javax.swing.JLabel jLblCvsAtivo;
    private javax.swing.JLabel jLblCvsCodigo;
    private javax.swing.JLabel jLblCvsCpf;
    private javax.swing.JLabel jLblCvsDataDeNascimento;
    private javax.swing.JLabel jLblCvsNome;
    private javax.swing.JLabel jLblCvsSenha;
    private javax.swing.JPasswordField jPwdCvsSenha;
    private javax.swing.JTextField jTxtCvsApelido;
    private javax.swing.JTextField jTxtCvsCodigo;
    private javax.swing.JTextField jTxtCvsNome;
    // End of variables declaration//GEN-END:variables
}
