package view;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class JFrmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form jFrameprincipal
     */
    public JFrmprincipal() {
        
        initComponents();
            this.setExtendedState(JFrmprincipal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jDlgUsuario = new javax.swing.JMenuItem();
        jDlgClientes = new javax.swing.JMenuItem();
        jDlgProdutos = new javax.swing.JMenuItem();
        jDlgSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        jDlgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camilly/usuario.png"))); // NOI18N
        jDlgUsuario.setText("Usuario");
        jDlgUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDlgUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jDlgUsuario);

        jDlgClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camilly/cliente.png"))); // NOI18N
        jDlgClientes.setText("clientes");
        jDlgClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDlgClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jDlgClientes);

        jDlgProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camilly/produto.png"))); // NOI18N
        jDlgProdutos.setText("funcionarios");
        jDlgProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDlgProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jDlgProdutos);

        jDlgSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camilly/sair.png"))); // NOI18N
        jDlgSair.setText("sair");
        jDlgSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDlgSairActionPerformed(evt);
            }
        });
        jMenu1.add(jDlgSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimento");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camilly/16103265.png"))); // NOI18N
        jMenuItem5.setText("vendas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDlgClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDlgClientesActionPerformed
        // TODO add your handling code here:
        JDlgCvsClientes dlg = new JDlgCvsClientes(this, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_jDlgClientesActionPerformed

    private void jDlgProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDlgProdutosActionPerformed
        // TODO add your handling code here:
        JDlgCvsFuncionario dlg = new JDlgCvsFuncionario(this, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_jDlgProdutosActionPerformed

    private void jDlgSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDlgSairActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jDlgSairActionPerformed

    private void jDlgUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDlgUsuarioActionPerformed
        // TODO add your handling code here: jDlgUsuarios dlg = new jDlgUsuarios(this, true);
        JDlgCvsUsuario dlg = new JDlgCvsUsuario(this, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_jDlgUsuarioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JDlgCvsVendasJoias jDlgVendasJoias = new JDlgCvsVendasJoias(this, true);
        jDlgVendasJoias.setLocationRelativeTo(this);
        jDlgVendasJoias.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jDlgClientes;
    private javax.swing.JMenuItem jDlgProdutos;
    private javax.swing.JMenuItem jDlgSair;
    private javax.swing.JMenuItem jDlgUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
