package cvs.view;

import bean.CvsFuncionarios;
import java.text.ParseException;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author user
 */
public class JDlgCvsFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form jDlgFuncionario
     *
     * @param parent
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    boolean pesquisando = false;

    public JDlgCvsFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);
        Util.habilitar(false, jTxtIdFuncionario, jTxtCvsNome, jFmtCvsDataNasc, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsTelefone, jTxtFuncao, jBtnCvsConfirmar, jBtnCvsCancelar);

        try {
            MaskFormatter mascara = new MaskFormatter("###.###.###-##");
            jFmtCvsCpf.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            jFmtCvsDataNasc.setFormatterFactory(new DefaultFormatterFactory(mascara));
            jFmtCvsDataNasc.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        try {
            MaskFormatter mascara = new MaskFormatter("(##) #####-####");
            jFmtCvsTelefone.setFormatterFactory(new DefaultFormatterFactory(mascara));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }

    public CvsFuncionarios viewBean() {
        CvsFuncionarios func = new CvsFuncionarios();

        func.setCvsIdFuncionario(Util.strToInt(jTxtIdFuncionario.getText()));
        func.setCvsNome(jTxtCvsNome.getText());
        func.setCvsFuncao(jTxtFuncao.getText());
        func.setCvsCpf(jFmtCvsCpf.getText());
        func.setCvsEmail(jTxtCvsEmail.getText());
        func.setCvsTelefone(jFmtCvsTelefone.getText());
        func.setCvsDataNascimento(Util.strToDate(jFmtCvsDataNasc.getText()));

        return func;
    }

    public void beanView(CvsFuncionarios func) {
        jTxtIdFuncionario.setText(Util.intToStr(func.getCvsIdFuncionario()));
        jTxtCvsNome.setText(func.getCvsNome());
        jTxtFuncao.setText(func.getCvsFuncao());
        jFmtCvsCpf.setText(func.getCvsCpf());
        jTxtCvsEmail.setText(func.getCvsEmail());
        jFmtCvsTelefone.setText(func.getCvsTelefone());
        jFmtCvsDataNasc.setText(Util.dateToStr(func.getCvsDataNascimento()));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jLblCvsUsuario = new javax.swing.JLabel();
        jLblCvsCpf = new javax.swing.JLabel();
        jLblCvsNome = new javax.swing.JLabel();
        jLblCvsDataDeNascimento = new javax.swing.JLabel();
        jLblCvsFuncao = new javax.swing.JLabel();
        jLblCvsEmail = new javax.swing.JLabel();
        jLblCvsTelefone = new javax.swing.JLabel();
        jTxtFuncao = new javax.swing.JTextField();
        jTxtCvsNome = new javax.swing.JTextField();
        jTxtIdFuncionario = new javax.swing.JTextField();
        jTxtCvsEmail = new javax.swing.JTextField();
        jBtnCvsCancelar = new javax.swing.JButton();
        jBtnCvsPesquisar = new javax.swing.JButton();
        jBtnCvsIncluir = new javax.swing.JButton();
        jBtnCvsAlterar = new javax.swing.JButton();
        jBtnCvsExcluir = new javax.swing.JButton();
        jBtnCvsConfirmar = new javax.swing.JButton();
        jFmtCvsDataNasc = new javax.swing.JFormattedTextField();
        jFmtCvsCpf = new javax.swing.JFormattedTextField();
        jFmtCvsTelefone = new javax.swing.JFormattedTextField();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCvsUsuario.setText("Funcionario");

        jLblCvsCpf.setText("Cpf");

        jLblCvsNome.setText("Nome");

        jLblCvsDataDeNascimento.setText("Data De Nascimento");

        jLblCvsFuncao.setText("Funcao");

        jLblCvsEmail.setText("Email");

        jLblCvsTelefone.setText("Telefone");

        jTxtFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFuncaoActionPerformed(evt);
            }
        });

        jTxtCvsEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCvsEmailActionPerformed(evt);
            }
        });

        jBtnCvsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCvsCancelar.setText("Cancelar");
        jBtnCvsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsCancelarActionPerformed(evt);
            }
        });

        jBtnCvsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnCvsPesquisar.setText("Pesquisar");
        jBtnCvsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsPesquisarActionPerformed(evt);
            }
        });

        jBtnCvsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnCvsIncluir.setText("Incluir");
        jBtnCvsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsIncluirActionPerformed(evt);
            }
        });

        jBtnCvsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnCvsAlterar.setText("Alterar");
        jBtnCvsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsAlterarActionPerformed(evt);
            }
        });

        jBtnCvsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnCvsExcluir.setText("Excluir");
        jBtnCvsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsExcluirActionPerformed(evt);
            }
        });

        jBtnCvsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jBtnCvsConfirmar.setText("Confirmar");
        jBtnCvsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCvsConfirmarActionPerformed(evt);
            }
        });

        jFmtCvsDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCvsDataNascActionPerformed(evt);
            }
        });

        jFmtCvsCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCvsCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jBtnCvsIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsAlterar)
                        .addGap(7, 7, 7)
                        .addComponent(jBtnCvsExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCvsPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFmtCvsTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFmtCvsCpf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFmtCvsDataNasc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblCvsDataDeNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblCvsUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblCvsNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblCvsEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblCvsCpf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblCvsTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblCvsFuncao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtIdFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                        .addComponent(jTxtCvsNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtFuncao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtCvsEmail, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCvsUsuario)
                .addGap(9, 9, 9)
                .addComponent(jTxtIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCvsNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCvsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCvsDataDeNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCvsDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCvsEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCvsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCvsCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCvsCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCvsTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCvsTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCvsFuncao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCvsAlterar)
                    .addComponent(jBtnCvsCancelar)
                    .addComponent(jBtnCvsPesquisar)
                    .addComponent(jBtnCvsConfirmar)
                    .addComponent(jBtnCvsExcluir)
                    .addComponent(jBtnCvsIncluir))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFuncaoActionPerformed
        // TODO add your handling code here:`
    }//GEN-LAST:event_jTxtFuncaoActionPerformed

    private void jBtnCvsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtIdFuncionario, jTxtCvsNome, jFmtCvsDataNasc, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsTelefone, jTxtFuncao, jBtnCvsConfirmar, jBtnCvsCancelar);
        Util.habilitar(false, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);

        Util.limpar(jTxtIdFuncionario, jTxtCvsNome, jFmtCvsDataNasc, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsTelefone, jTxtFuncao);

    }//GEN-LAST:event_jBtnCvsIncluirActionPerformed

    private void jBtnCvsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtIdFuncionario, jTxtCvsNome, jFmtCvsDataNasc, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsTelefone, jTxtFuncao, jBtnCvsConfirmar, jBtnCvsCancelar);
        Util.habilitar(true, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);

    }//GEN-LAST:event_jBtnCvsConfirmarActionPerformed

    private void jBtnCvsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtIdFuncionario, jTxtCvsNome, jFmtCvsDataNasc, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsTelefone, jTxtFuncao, jBtnCvsConfirmar, jBtnCvsCancelar);
        Util.habilitar(true, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);

    }//GEN-LAST:event_jBtnCvsCancelarActionPerformed

    private void jTxtCvsEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCvsEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCvsEmailActionPerformed

    private void jBtnCvsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsExcluirActionPerformed
        // TODO add your handling code here:
        if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar um usuário primeiro");
        } else {
            Util.perguntar("Você deseja excluir?");
            Util.limpar(jTxtIdFuncionario, jTxtCvsNome, jFmtCvsDataNasc, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsTelefone, jTxtFuncao);
        }
    }//GEN-LAST:event_jBtnCvsExcluirActionPerformed

    private void jBtnCvsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgCvsFuncionarioPesquisar jDlgCvsFuncionarioPesquisar = new JDlgCvsFuncionarioPesquisar(null, true);
        jDlgCvsFuncionarioPesquisar.setTelaPai(this);
        jDlgCvsFuncionarioPesquisar.setVisible(true);
        pesquisando = true;

    }//GEN-LAST:event_jBtnCvsPesquisarActionPerformed

    private void jFmtCvsCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCvsCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCvsCpfActionPerformed

    private void jFmtCvsDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCvsDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCvsDataNascActionPerformed

    private void jBtnCvsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCvsAlterarActionPerformed
        Util.habilitar(true, jTxtCvsNome, jFmtCvsDataNasc, jTxtCvsEmail, jFmtCvsCpf, jFmtCvsTelefone, jTxtFuncao, jBtnCvsConfirmar, jBtnCvsCancelar);
        Util.habilitar(false, jBtnCvsAlterar, jBtnCvsExcluir, jBtnCvsPesquisar, jBtnCvsIncluir);

    }//GEN-LAST:event_jBtnCvsAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCvsFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCvsFuncionario dialog = new JDlgCvsFuncionario(new javax.swing.JFrame(), true); // se quiser, pode renomear a classe para JDlgFuncionario
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton jBtnCvsAlterar;
    private javax.swing.JButton jBtnCvsCancelar;
    private javax.swing.JButton jBtnCvsConfirmar;
    private javax.swing.JButton jBtnCvsExcluir;
    private javax.swing.JButton jBtnCvsIncluir;
    private javax.swing.JButton jBtnCvsPesquisar;
    private javax.swing.JFormattedTextField jFmtCvsCpf;
    private javax.swing.JFormattedTextField jFmtCvsDataNasc;
    private javax.swing.JFormattedTextField jFmtCvsTelefone;
    private javax.swing.JLabel jLblCvsCpf;
    private javax.swing.JLabel jLblCvsDataDeNascimento;
    private javax.swing.JLabel jLblCvsEmail;
    private javax.swing.JLabel jLblCvsFuncao;
    private javax.swing.JLabel jLblCvsNome;
    private javax.swing.JLabel jLblCvsTelefone;
    private javax.swing.JLabel jLblCvsUsuario;
    private javax.swing.JTextField jTxtCvsEmail;
    private javax.swing.JTextField jTxtCvsNome;
    private javax.swing.JTextField jTxtFuncao;
    private javax.swing.JTextField jTxtIdFuncionario;
    // End of variables declaration//GEN-END:variables

}
