package bean;
// Generated 09/12/2025 21:39:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvsClientes generated by hbm2java
 */
@Entity
@Table(name="cvs_clientes"
    ,catalog="db_camilly_souza"
)
public class CvsClientes  implements java.io.Serializable {


     private int cvsIdCliente;
     private String cvsNome;
     private String cvsEmail;
     private String cvsCidade;
     private String cvsRg;
     private Date cvsDataNascimento;
     private String cvsTelefone;
     private String cvsEndereco;
     private String cvsSexo;
     private Date cvsDataCadastro;
     private String cvsCpf;
     private String cvsEstado;
     private String cvsCep;
     private String cvsBairro;
     private String cvsNacionalidade;

    public CvsClientes() {
    }

    public CvsClientes(String cvsNome, String cvsEmail, String cvsCidade, String cvsRg, Date cvsDataNascimento, String cvsTelefone, String cvsEndereco, String cvsSexo, Date cvsDataCadastro, String cvsCpf, String cvsEstado, String cvsCep, String cvsBairro, String cvsNacionalidade) {
       this.cvsNome = cvsNome;
       this.cvsEmail = cvsEmail;
       this.cvsCidade = cvsCidade;
       this.cvsRg = cvsRg;
       this.cvsDataNascimento = cvsDataNascimento;
       this.cvsTelefone = cvsTelefone;
       this.cvsEndereco = cvsEndereco;
       this.cvsSexo = cvsSexo;
       this.cvsDataCadastro = cvsDataCadastro;
       this.cvsCpf = cvsCpf;
       this.cvsEstado = cvsEstado;
       this.cvsCep = cvsCep;
       this.cvsBairro = cvsBairro;
       this.cvsNacionalidade = cvsNacionalidade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cvs_id_cliente", unique=true, nullable=false)
    public int getCvsIdCliente() {
        return this.cvsIdCliente;
    }
    
    public void setCvsIdCliente(int cvsIdCliente) {
        this.cvsIdCliente = cvsIdCliente;
    }

    
    @Column(name="cvs_nome", length=150)
    public String getCvsNome() {
        return this.cvsNome;
    }
    
    public void setCvsNome(String cvsNome) {
        this.cvsNome = cvsNome;
    }

    
    @Column(name="cvs_email", length=150)
    public String getCvsEmail() {
        return this.cvsEmail;
    }
    
    public void setCvsEmail(String cvsEmail) {
        this.cvsEmail = cvsEmail;
    }

    
    @Column(name="cvs_cidade", length=150)
    public String getCvsCidade() {
        return this.cvsCidade;
    }
    
    public void setCvsCidade(String cvsCidade) {
        this.cvsCidade = cvsCidade;
    }

    
    @Column(name="cvs_rg", length=11)
    public String getCvsRg() {
        return this.cvsRg;
    }
    
    public void setCvsRg(String cvsRg) {
        this.cvsRg = cvsRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cvs_data_nascimento", length=10)
    public Date getCvsDataNascimento() {
        return this.cvsDataNascimento;
    }
    
    public void setCvsDataNascimento(Date cvsDataNascimento) {
        this.cvsDataNascimento = cvsDataNascimento;
    }

    
    @Column(name="cvs_telefone", length=16)
    public String getCvsTelefone() {
        return this.cvsTelefone;
    }
    
    public void setCvsTelefone(String cvsTelefone) {
        this.cvsTelefone = cvsTelefone;
    }

    
    @Column(name="cvs_endereco", length=150)
    public String getCvsEndereco() {
        return this.cvsEndereco;
    }
    
    public void setCvsEndereco(String cvsEndereco) {
        this.cvsEndereco = cvsEndereco;
    }

    
    @Column(name="cvs_sexo", length=1)
    public String getCvsSexo() {
        return this.cvsSexo;
    }
    
    public void setCvsSexo(String cvsSexo) {
        this.cvsSexo = cvsSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cvs_data_cadastro", length=10)
    public Date getCvsDataCadastro() {
        return this.cvsDataCadastro;
    }
    
    public void setCvsDataCadastro(Date cvsDataCadastro) {
        this.cvsDataCadastro = cvsDataCadastro;
    }

    
    @Column(name="cvs_cpf", length=11)
    public String getCvsCpf() {
        return this.cvsCpf;
    }
    
    public void setCvsCpf(String cvsCpf) {
        this.cvsCpf = cvsCpf;
    }

    
    @Column(name="cvs_estado", length=2)
    public String getCvsEstado() {
        return this.cvsEstado;
    }
    
    public void setCvsEstado(String cvsEstado) {
        this.cvsEstado = cvsEstado;
    }

    
    @Column(name="cvs_cep", length=9)
    public String getCvsCep() {
        return this.cvsCep;
    }
    
    public void setCvsCep(String cvsCep) {
        this.cvsCep = cvsCep;
    }

    
    @Column(name="cvs_bairro", length=55)
    public String getCvsBairro() {
        return this.cvsBairro;
    }
    
    public void setCvsBairro(String cvsBairro) {
        this.cvsBairro = cvsBairro;
    }

    
    @Column(name="cvs_nacionalidade", length=50)
    public String getCvsNacionalidade() {
        return this.cvsNacionalidade;
    }
    
    public void setCvsNacionalidade(String cvsNacionalidade) {
        this.cvsNacionalidade = cvsNacionalidade;
    }
}


