package bean;
<<<<<<< HEAD
// Generated 09/12/2025 21:39:33 by Hibernate Tools 4.3.1
=======
// Generated 07/10/2025 20:07:58 by Hibernate Tools 4.3.1
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvsClientes generated by hbm2java
 */
@Entity
@Table(name="cvs_clientes"
    ,catalog="db_camilly_souza"
)
public class CvsClientes  implements java.io.Serializable {


<<<<<<< HEAD
     private Integer cvsIdCliente;
=======
     private int cvsIdCliente;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
     private String cvsIdNome;
     private String cvsEmail;
     private String cvsCidade;
     private String cvsRg;
     private Date cvsDataNascimento;
     private String cvsTelefone;
     private String cvsEndereco;
     private String cvsSexo;
     private Date cvsDataCadastro;
     private String cvsCpf;
<<<<<<< HEAD
     private String cvsEstado;
     private String cvsCep;
     private String cvsBairro;
     private String cvsNacionalidade;
     private Set cvsVendases = new HashSet(0);
=======
     private String cvsEstdado;
     private String cvsCep;
     private String cvsBairro;
     private String cvsNacionalidade;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1

    public CvsClientes() {
    }

<<<<<<< HEAD
    public CvsClientes(String cvsIdNome, String cvsEmail, String cvsCidade, String cvsRg, Date cvsDataNascimento, String cvsTelefone, String cvsEndereco, String cvsSexo, Date cvsDataCadastro, String cvsCpf, String cvsEstado, String cvsCep, String cvsBairro, String cvsNacionalidade, Set cvsVendases) {
=======
    public CvsClientes(String cvsIdNome, String cvsEmail, String cvsCidade, String cvsRg, Date cvsDataNascimento, String cvsTelefone, String cvsEndereco, String cvsSexo, Date cvsDataCadastro, String cvsCpf, String cvsEstdado, String cvsCep, String cvsBairro, String cvsNacionalidade) {
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
       this.cvsIdNome = cvsIdNome;
       this.cvsEmail = cvsEmail;
       this.cvsCidade = cvsCidade;
       this.cvsRg = cvsRg;
       this.cvsDataNascimento = cvsDataNascimento;
       this.cvsTelefone = cvsTelefone;
       this.cvsEndereco = cvsEndereco;
       this.cvsSexo = cvsSexo;
       this.cvsDataCadastro = cvsDataCadastro;
       this.cvsCpf = cvsCpf;
<<<<<<< HEAD
       this.cvsEstado = cvsEstado;
       this.cvsCep = cvsCep;
       this.cvsBairro = cvsBairro;
       this.cvsNacionalidade = cvsNacionalidade;
       this.cvsVendases = cvsVendases;
=======
       this.cvsEstdado = cvsEstdado;
       this.cvsCep = cvsCep;
       this.cvsBairro = cvsBairro;
       this.cvsNacionalidade = cvsNacionalidade;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cvs_id_cliente", unique=true, nullable=false)
<<<<<<< HEAD
    public Integer getCvsIdCliente() {
        return this.cvsIdCliente;
    }
    
    public void setCvsIdCliente(Integer cvsIdCliente) {
=======
    public int getCvsIdCliente() {
        return this.cvsIdCliente;
    }
    
    public void setCvsIdCliente(int cvsIdCliente) {
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
        this.cvsIdCliente = cvsIdCliente;
    }

    
    @Column(name="cvs_id_nome", length=150)
    public String getCvsIdNome() {
        return this.cvsIdNome;
    }
    
    public void setCvsIdNome(String cvsIdNome) {
        this.cvsIdNome = cvsIdNome;
    }

    
    @Column(name="cvs_email", length=150)
    public String getCvsEmail() {
        return this.cvsEmail;
    }
    
    public void setCvsEmail(String cvsEmail) {
        this.cvsEmail = cvsEmail;
    }

    
    @Column(name="cvs_cidade", length=150)
    public String getCvsCidade() {
        return this.cvsCidade;
    }
    
    public void setCvsCidade(String cvsCidade) {
        this.cvsCidade = cvsCidade;
    }

    
    @Column(name="cvs_rg", length=11)
    public String getCvsRg() {
        return this.cvsRg;
    }
    
    public void setCvsRg(String cvsRg) {
        this.cvsRg = cvsRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cvs_data_nascimento", length=10)
    public Date getCvsDataNascimento() {
        return this.cvsDataNascimento;
    }
    
    public void setCvsDataNascimento(Date cvsDataNascimento) {
        this.cvsDataNascimento = cvsDataNascimento;
    }

    
    @Column(name="cvs_telefone", length=16)
    public String getCvsTelefone() {
        return this.cvsTelefone;
    }
    
    public void setCvsTelefone(String cvsTelefone) {
        this.cvsTelefone = cvsTelefone;
    }

    
    @Column(name="cvs_endereco", length=150)
    public String getCvsEndereco() {
        return this.cvsEndereco;
    }
    
    public void setCvsEndereco(String cvsEndereco) {
        this.cvsEndereco = cvsEndereco;
    }

    
    @Column(name="cvs_sexo", length=1)
    public String getCvsSexo() {
        return this.cvsSexo;
    }
    
    public void setCvsSexo(String cvsSexo) {
        this.cvsSexo = cvsSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cvs_data_cadastro", length=10)
    public Date getCvsDataCadastro() {
        return this.cvsDataCadastro;
    }
    
    public void setCvsDataCadastro(Date cvsDataCadastro) {
        this.cvsDataCadastro = cvsDataCadastro;
    }

    
    @Column(name="cvs_cpf", length=11)
    public String getCvsCpf() {
        return this.cvsCpf;
    }
    
    public void setCvsCpf(String cvsCpf) {
        this.cvsCpf = cvsCpf;
    }

    
<<<<<<< HEAD
    @Column(name="cvs_estado", length=2)
    public String getCvsEstado() {
        return this.cvsEstado;
    }
    
    public void setCvsEstado(String cvsEstado) {
        this.cvsEstado = cvsEstado;
=======
    @Column(name="cvs_estdado", length=2)
    public String getCvsEstdado() {
        return this.cvsEstdado;
    }
    
    public void setCvsEstdado(String cvsEstdado) {
        this.cvsEstdado = cvsEstdado;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    }

    
    @Column(name="cvs_cep", length=9)
    public String getCvsCep() {
        return this.cvsCep;
    }
    
    public void setCvsCep(String cvsCep) {
        this.cvsCep = cvsCep;
    }

    
    @Column(name="cvs_bairro", length=55)
    public String getCvsBairro() {
        return this.cvsBairro;
    }
    
    public void setCvsBairro(String cvsBairro) {
        this.cvsBairro = cvsBairro;
    }

    
<<<<<<< HEAD
    @Column(name="cvs_nacionalidade", length=50)
=======
    @Column(name="cvs-nacionalidade", length=50)
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    public String getCvsNacionalidade() {
        return this.cvsNacionalidade;
    }
    
    public void setCvsNacionalidade(String cvsNacionalidade) {
        this.cvsNacionalidade = cvsNacionalidade;
    }

<<<<<<< HEAD
@OneToMany(fetch=FetchType.LAZY, mappedBy="cvsClientes")
    public Set getCvsVendases() {
        return this.cvsVendases;
    }
    
    public void setCvsVendases(Set cvsVendases) {
        this.cvsVendases = cvsVendases;
    }
=======

>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1




}


