package bean;
// Generated 09/12/2025 21:39:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvsFuncionarios generated by hbm2java
 */
@Entity
@Table(name="cvs_funcionarios"
    ,catalog="db_camilly_souza"
)
public class CvsFuncionarios  implements java.io.Serializable {


     private int cvsIdFuncionario;
     private String cvsFuncao;
     private Date cvsDataNascimento;
     private String cvsCpf;
     private String cvsEmail;
     private String cvsNome;
     private String cvsTelefone;

    public CvsFuncionarios() {
    }

	
    public CvsFuncionarios(int cvsIdFuncionario) {
        this.cvsIdFuncionario = cvsIdFuncionario;
    }
    public CvsFuncionarios(int cvsIdFuncionario, String cvsFuncao, Date cvsDataNascimento, String cvsCpf, String cvsEmail, String cvsNome, String cvsTelefone, Set cvsVendases) {
       this.cvsIdFuncionario = cvsIdFuncionario;
       this.cvsFuncao = cvsFuncao;
       this.cvsDataNascimento = cvsDataNascimento;
       this.cvsCpf = cvsCpf;
       this.cvsEmail = cvsEmail;
       this.cvsNome = cvsNome;
       this.cvsTelefone = cvsTelefone;
    }
   
     @Id 

    
    @Column(name="cvs_id_funcionario", unique=true, nullable=false)
    public int getCvsIdFuncionario() {
        return this.cvsIdFuncionario;
    }
    
    public void setCvsIdFuncionario(int cvsIdFuncionario) {
        this.cvsIdFuncionario = cvsIdFuncionario;
    }

    
    @Column(name="cvs_funcao", length=100)
    public String getCvsFuncao() {
        return this.cvsFuncao;
    }
    
    public void setCvsFuncao(String cvsFuncao) {
        this.cvsFuncao = cvsFuncao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cvs_data_nascimento", length=10)
    public Date getCvsDataNascimento() {
        return this.cvsDataNascimento;
    }
    
    public void setCvsDataNascimento(Date cvsDataNascimento) {
        this.cvsDataNascimento = cvsDataNascimento;
    }

    
    @Column(name="cvs_cpf", length=14)
    public String getCvsCpf() {
        return this.cvsCpf;
    }
    
    public void setCvsCpf(String cvsCpf) {
        this.cvsCpf = cvsCpf;
    }

    
    @Column(name="cvs_email", length=150)
    public String getCvsEmail() {
        return this.cvsEmail;
    }
    
    public void setCvsEmail(String cvsEmail) {
        this.cvsEmail = cvsEmail;
    }

    
    @Column(name="cvs_nome", length=150)
    public String getCvsNome() {
        return this.cvsNome;
    }
    
    public void setCvsNome(String cvsNome) {
        this.cvsNome = cvsNome;
    }

    
    @Column(name="cvs_telefone", length=20)
    public String getCvsTelefone() {
        return this.cvsTelefone;
    }
    
    public void setCvsTelefone(String cvsTelefone) {
        this.cvsTelefone = cvsTelefone;
    }

    @Override
    public String toString() {
        return this.getCvsNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof CvsFuncionarios) {
            CvsFuncionarios o = (CvsFuncionarios) obj;
            if (o.getCvsIdFuncionario()== this.getCvsIdFuncionario()) {
                return true;
            }
        }
        return false;
    }
}


