package bean;
<<<<<<< HEAD
// Generated 09/12/2025 21:39:33 by Hibernate Tools 4.3.1
=======
// Generated 07/10/2025 20:07:58 by Hibernate Tools 4.3.1
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
<<<<<<< HEAD
=======
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvsFuncionarios generated by hbm2java
 */
@Entity
@Table(name="cvs_funcionarios"
    ,catalog="db_camilly_souza"
)
public class CvsFuncionarios  implements java.io.Serializable {


<<<<<<< HEAD
     private int cvsIdFuncionario;
=======
     private int cvsIdUsuario;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
     private String cvsFuncao;
     private Date cvsDataNascimento;
     private String cvsCpf;
     private String cvsEmail;
     private String cvsNome;
     private String cvsTelefone;
<<<<<<< HEAD
     private Set cvsVendases = new HashSet(0);
=======
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1

    public CvsFuncionarios() {
    }

<<<<<<< HEAD
	
    public CvsFuncionarios(int cvsIdFuncionario) {
        this.cvsIdFuncionario = cvsIdFuncionario;
    }
    public CvsFuncionarios(int cvsIdFuncionario, String cvsFuncao, Date cvsDataNascimento, String cvsCpf, String cvsEmail, String cvsNome, String cvsTelefone, Set cvsVendases) {
       this.cvsIdFuncionario = cvsIdFuncionario;
=======
    public CvsFuncionarios(String cvsFuncao, Date cvsDataNascimento, String cvsCpf, String cvsEmail, String cvsNome, String cvsTelefone) {
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
       this.cvsFuncao = cvsFuncao;
       this.cvsDataNascimento = cvsDataNascimento;
       this.cvsCpf = cvsCpf;
       this.cvsEmail = cvsEmail;
       this.cvsNome = cvsNome;
       this.cvsTelefone = cvsTelefone;
<<<<<<< HEAD
       this.cvsVendases = cvsVendases;
    }
   
     @Id 

    
    @Column(name="cvs_id_funcionario", unique=true, nullable=false)
    public int getCvsIdFuncionario() {
        return this.cvsIdFuncionario;
    }
    
    public void setCvsIdFuncionario(int cvsIdFuncionario) {
        this.cvsIdFuncionario = cvsIdFuncionario;
=======
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cvs_id_usuario", unique=true, nullable=false)
    public int getCvsIdUsuario() {
        return this.cvsIdUsuario;
    }
    
    public void setCvsIdUsuario(int cvsIdUsuario) {
        this.cvsIdUsuario = cvsIdUsuario;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    }

    
    @Column(name="cvs_funcao", length=100)
    public String getCvsFuncao() {
        return this.cvsFuncao;
    }
    
    public void setCvsFuncao(String cvsFuncao) {
        this.cvsFuncao = cvsFuncao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cvs_data_nascimento", length=10)
    public Date getCvsDataNascimento() {
        return this.cvsDataNascimento;
    }
    
    public void setCvsDataNascimento(Date cvsDataNascimento) {
        this.cvsDataNascimento = cvsDataNascimento;
    }

    
    @Column(name="cvs_cpf", length=14)
    public String getCvsCpf() {
        return this.cvsCpf;
    }
    
    public void setCvsCpf(String cvsCpf) {
        this.cvsCpf = cvsCpf;
    }

    
    @Column(name="cvs_email", length=150)
    public String getCvsEmail() {
        return this.cvsEmail;
    }
    
    public void setCvsEmail(String cvsEmail) {
        this.cvsEmail = cvsEmail;
    }

    
    @Column(name="cvs_nome", length=150)
    public String getCvsNome() {
        return this.cvsNome;
    }
    
    public void setCvsNome(String cvsNome) {
        this.cvsNome = cvsNome;
    }

    
    @Column(name="cvs_telefone", length=20)
    public String getCvsTelefone() {
        return this.cvsTelefone;
    }
    
    public void setCvsTelefone(String cvsTelefone) {
        this.cvsTelefone = cvsTelefone;
    }

<<<<<<< HEAD
@OneToMany(fetch=FetchType.LAZY, mappedBy="cvsFuncionarios")
    public Set getCvsVendases() {
        return this.cvsVendases;
    }
    
    public void setCvsVendases(Set cvsVendases) {
        this.cvsVendases = cvsVendases;
    }
=======

>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1




}


