package bean;
// Generated 07/10/2025 20:07:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvsJoias generated by hbm2java
 */
@Entity
@Table(name="cvs_joias"
    ,catalog="db_camilly_souza"
)
public class CvsJoias  implements java.io.Serializable {


     private int cvsIdCodigo;
     private double cvsPeso;
     private String cvsNome;
     private double cvsPreco;
     private String cvsTipo;
     private String cvsDescricao;
     private String cvsMaterial;

    public CvsJoias() {
    }

    public CvsJoias(double cvsPeso, String cvsNome, double cvsPreco, String cvsTipo, String cvsDescricao, String cvsMaterial) {
       this.cvsPeso = cvsPeso;
       this.cvsNome = cvsNome;
       this.cvsPreco = cvsPreco;
       this.cvsTipo = cvsTipo;
       this.cvsDescricao = cvsDescricao;
       this.cvsMaterial = cvsMaterial;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cvs_id_codigo", unique=true, nullable=false)
    public int getCvsIdCodigo() {
        return this.cvsIdCodigo;
    }
    
    public void setCvsIdCodigo(int cvsIdCodigo) {
        this.cvsIdCodigo = cvsIdCodigo;
    }

    
    @Column(name="cvs_peso", precision=10)
    public double getCvsPeso() {
        return this.cvsPeso;
    }
    
    public void setCvsPeso(double cvsPeso) {
        this.cvsPeso = cvsPeso;
    }

    
    @Column(name="cvs_nome", length=100)
    public String getCvsNome() {
        return this.cvsNome;
    }
    
    public void setCvsNome(String cvsNome) {
        this.cvsNome = cvsNome;
    }

    
    @Column(name="cvs_preco", precision=10)
    public double getCvsPreco() {
        return this.cvsPreco;
    }
    
    public void setCvsPreco(double cvsPreco) {
        this.cvsPreco = cvsPreco;
    }

    
    @Column(name="cvs_tipo", length=50)
    public String getCvsTipo() {
        return this.cvsTipo;
    }
    
    public void setCvsTipo(String cvsTipo) {
        this.cvsTipo = cvsTipo;
    }

    
    @Column(name="cvs_descricao", length=65535)
    public String getCvsDescricao() {
        return this.cvsDescricao;
    }
    
    public void setCvsDescricao(String cvsDescricao) {
        this.cvsDescricao = cvsDescricao;
    }

    
    @Column(name="cvs_material", length=100)
    public String getCvsMaterial() {
        return this.cvsMaterial;
    }
    
    public void setCvsMaterial(String cvsMaterial) {
        this.cvsMaterial = cvsMaterial;
    }






}


