package bean;
<<<<<<< HEAD
// Generated 09/12/2025 21:39:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
=======
// Generated 07/10/2025 20:07:58 by Hibernate Tools 4.3.1


>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvsJoias generated by hbm2java
 */
@Entity
@Table(name="cvs_joias"
    ,catalog="db_camilly_souza"
)
public class CvsJoias  implements java.io.Serializable {


<<<<<<< HEAD
     private Integer cvsIdJoias;
     private BigDecimal cvsPeso;
     private String cvsNome;
     private BigDecimal cvsPreco;
     private String cvsTipo;
     private String cvsDescricao;
     private String cvsMaterial;
     private Set cvsVendasjoiases = new HashSet(0);
=======
     private int cvsIdCodigo;
     private double cvsPeso;
     private String cvsNome;
     private double cvsPreco;
     private String cvsTipo;
     private String cvsDescricao;
     private String cvsMaterial;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1

    public CvsJoias() {
    }

<<<<<<< HEAD
    public CvsJoias(BigDecimal cvsPeso, String cvsNome, BigDecimal cvsPreco, String cvsTipo, String cvsDescricao, String cvsMaterial, Set cvsVendasjoiases) {
=======
    public CvsJoias(double cvsPeso, String cvsNome, double cvsPreco, String cvsTipo, String cvsDescricao, String cvsMaterial) {
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
       this.cvsPeso = cvsPeso;
       this.cvsNome = cvsNome;
       this.cvsPreco = cvsPreco;
       this.cvsTipo = cvsTipo;
       this.cvsDescricao = cvsDescricao;
       this.cvsMaterial = cvsMaterial;
<<<<<<< HEAD
       this.cvsVendasjoiases = cvsVendasjoiases;
=======
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
<<<<<<< HEAD
    @Column(name="cvs_id_joias", unique=true, nullable=false)
    public Integer getCvsIdJoias() {
        return this.cvsIdJoias;
    }
    
    public void setCvsIdJoias(Integer cvsIdJoias) {
        this.cvsIdJoias = cvsIdJoias;
=======
    @Column(name="cvs_id_codigo", unique=true, nullable=false)
    public int getCvsIdCodigo() {
        return this.cvsIdCodigo;
    }
    
    public void setCvsIdCodigo(int cvsIdCodigo) {
        this.cvsIdCodigo = cvsIdCodigo;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    }

    
    @Column(name="cvs_peso", precision=10)
<<<<<<< HEAD
    public BigDecimal getCvsPeso() {
        return this.cvsPeso;
    }
    
    public void setCvsPeso(BigDecimal cvsPeso) {
=======
    public double getCvsPeso() {
        return this.cvsPeso;
    }
    
    public void setCvsPeso(double cvsPeso) {
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
        this.cvsPeso = cvsPeso;
    }

    
    @Column(name="cvs_nome", length=100)
    public String getCvsNome() {
        return this.cvsNome;
    }
    
    public void setCvsNome(String cvsNome) {
        this.cvsNome = cvsNome;
    }

    
    @Column(name="cvs_preco", precision=10)
<<<<<<< HEAD
    public BigDecimal getCvsPreco() {
        return this.cvsPreco;
    }
    
    public void setCvsPreco(BigDecimal cvsPreco) {
=======
    public double getCvsPreco() {
        return this.cvsPreco;
    }
    
    public void setCvsPreco(double cvsPreco) {
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
        this.cvsPreco = cvsPreco;
    }

    
    @Column(name="cvs_tipo", length=50)
    public String getCvsTipo() {
        return this.cvsTipo;
    }
    
    public void setCvsTipo(String cvsTipo) {
        this.cvsTipo = cvsTipo;
    }

    
<<<<<<< HEAD
    @Column(name="cvs_descricao", length=50)
=======
    @Column(name="cvs_descricao", length=65535)
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    public String getCvsDescricao() {
        return this.cvsDescricao;
    }
    
    public void setCvsDescricao(String cvsDescricao) {
        this.cvsDescricao = cvsDescricao;
    }

    
    @Column(name="cvs_material", length=100)
    public String getCvsMaterial() {
        return this.cvsMaterial;
    }
    
    public void setCvsMaterial(String cvsMaterial) {
        this.cvsMaterial = cvsMaterial;
    }

<<<<<<< HEAD
@OneToMany(fetch=FetchType.LAZY, mappedBy="cvsJoias")
    public Set getCvsVendasjoiases() {
        return this.cvsVendasjoiases;
    }
    
    public void setCvsVendasjoiases(Set cvsVendasjoiases) {
        this.cvsVendasjoiases = cvsVendasjoiases;
    }
=======

>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1




}


