package bean;
// Generated 09/12/2025 21:39:33 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CvsJoias generated by hbm2java
 */
@Entity
@Table(name="cvs_joias"
    ,catalog="db_camilly_souza"
)
public class CvsJoias  implements java.io.Serializable {


     private int cvsIdJoias;
     private Double cvsPeso;
     private String cvsNome;
     private Double cvsPreco;
     private String cvsTipo;
     private String cvsDescricao;
     private String cvsMaterial;

    public CvsJoias() {
    }

    public CvsJoias(Double cvsPeso, String cvsNome, Double cvsPreco, String cvsTipo, String cvsDescricao, String cvsMaterial) {
       this.cvsPeso = cvsPeso;
       this.cvsNome = cvsNome;
       this.cvsPreco = cvsPreco;
       this.cvsTipo = cvsTipo;
       this.cvsDescricao = cvsDescricao;
       this.cvsMaterial = cvsMaterial;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cvs_id_joias", unique=true, nullable=false)
    public int getCvsIdJoias() {
        return this.cvsIdJoias;
    }
    
    public void setCvsIdJoias(int cvsIdJoias) {
        this.cvsIdJoias = cvsIdJoias;
    }

    
    @Column(name="cvs_peso", precision=10)
    public Double getCvsPeso() {
        return this.cvsPeso;
    }
    
    public void setCvsPeso(Double cvsPeso) {
        this.cvsPeso = cvsPeso;
    }

    
    @Column(name="cvs_nome", length=100)
    public String getCvsNome() {
        return this.cvsNome;
    }
    
    public void setCvsNome(String cvsNome) {
        this.cvsNome = cvsNome;
    }

    
    @Column(name="cvs_preco", precision=10)
    public Double getCvsPreco() {
        return this.cvsPreco;
    }
    
    public void setCvsPreco(Double cvsPreco) {
        this.cvsPreco = cvsPreco;
    }

    
    @Column(name="cvs_tipo", length=50)
    public String getCvsTipo() {
        return this.cvsTipo;
    }
    
    public void setCvsTipo(String cvsTipo) {
        this.cvsTipo = cvsTipo;
    }

    
    @Column(name="cvs_descricao", length=50)
    public String getCvsDescricao() {
        return this.cvsDescricao;
    }
    
    public void setCvsDescricao(String cvsDescricao) {
        this.cvsDescricao = cvsDescricao;
    }

    
    @Column(name="cvs_material", length=100)
    public String getCvsMaterial() {
        return this.cvsMaterial;
    }
    
    public void setCvsMaterial(String cvsMaterial) {
        this.cvsMaterial = cvsMaterial;
    }

    @Override
    public String toString() {
        return this.getCvsNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof CvsJoias) {
            CvsJoias o = (CvsJoias) obj;
            if (o.getCvsIdJoias()== this.getCvsIdJoias()) {
                return true;
            }
        }
        return false;
    }
}