package bean;
<<<<<<< HEAD
// Generated 09/12/2025 21:39:33 by Hibernate Tools 4.3.1
=======
// Generated 07/10/2025 20:07:58 by Hibernate Tools 4.3.1
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvsUsuario generated by hbm2java
 */
@Entity
@Table(name="cvs_usuario"
    ,catalog="db_camilly_souza"
)
public class CvsUsuario  implements java.io.Serializable {


<<<<<<< HEAD
     private Integer cvsIdUsuario;
=======
     private int cvsIdcodigo;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
     private String cvsNome;
     private String cvsApelido;
     private String cvsSenha;
     private Date cvsDataNascimento;
<<<<<<< HEAD
     private Integer cvsAtivo;
=======
     private int cvsAtivo;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
     private String cvsCpf;

    public CvsUsuario() {
    }

<<<<<<< HEAD
    public CvsUsuario(String cvsNome, String cvsApelido, String cvsSenha, Date cvsDataNascimento, Integer cvsAtivo, String cvsCpf) {
=======
    public CvsUsuario(String cvsNome, String cvsApelido, String cvsSenha, Date cvsDataNascimento, int cvsAtivo, String cvsCpf) {
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
       this.cvsNome = cvsNome;
       this.cvsApelido = cvsApelido;
       this.cvsSenha = cvsSenha;
       this.cvsDataNascimento = cvsDataNascimento;
       this.cvsAtivo = cvsAtivo;
       this.cvsCpf = cvsCpf;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
<<<<<<< HEAD
    @Column(name="cvs_id_usuario", unique=true, nullable=false)
    public Integer getCvsIdUsuario() {
        return this.cvsIdUsuario;
    }
    
    public void setCvsIdUsuario(Integer cvsIdUsuario) {
        this.cvsIdUsuario = cvsIdUsuario;
=======
    @Column(name="cvs_idcodigo", unique=true, nullable=false)
    public int getCvsIdcodigo() {
        return this.cvsIdcodigo;
    }
    
    public void setCvsIdcodigo(int cvsIdcodigo) {
        this.cvsIdcodigo = cvsIdcodigo;
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    }

    
    @Column(name="cvs_nome", length=150)
    public String getCvsNome() {
        return this.cvsNome;
    }
    
    public void setCvsNome(String cvsNome) {
        this.cvsNome = cvsNome;
    }

    
    @Column(name="cvs_apelido", length=100)
    public String getCvsApelido() {
        return this.cvsApelido;
    }
    
    public void setCvsApelido(String cvsApelido) {
        this.cvsApelido = cvsApelido;
    }

    
    @Column(name="cvs_senha", length=50)
    public String getCvsSenha() {
        return this.cvsSenha;
    }
    
    public void setCvsSenha(String cvsSenha) {
        this.cvsSenha = cvsSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cvs_data_nascimento", length=10)
    public Date getCvsDataNascimento() {
        return this.cvsDataNascimento;
    }
    
    public void setCvsDataNascimento(Date cvsDataNascimento) {
        this.cvsDataNascimento = cvsDataNascimento;
    }

    
    @Column(name="cvs_ativo")
<<<<<<< HEAD
    public Integer getCvsAtivo() {
        return this.cvsAtivo;
    }
    
    public void setCvsAtivo(Integer cvsAtivo) {
=======
    public int getCvsAtivo() {
        return this.cvsAtivo;
    }
    
    public void setCvsAtivo(int cvsAtivo) {
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
        this.cvsAtivo = cvsAtivo;
    }

    
<<<<<<< HEAD
    @Column(name="cvs_cpf", length=14)
=======
    @Column(name="cvs_cpf", length=11)
>>>>>>> 2dfacaf3e419345d3e623761ad0a9212d7fceed1
    public String getCvsCpf() {
        return this.cvsCpf;
    }
    
    public void setCvsCpf(String cvsCpf) {
        this.cvsCpf = cvsCpf;
    }




}


