package bean;
// Generated 09/12/2025 21:39:33 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CvsVendasjoias generated by hbm2java
 */
@Entity
@Table(name="cvs_vendasjoias"
    ,catalog="db_camilly_souza"
)
public class CvsVendasjoias  implements java.io.Serializable {


     private int cvsIdVendasJoias;
     private CvsJoias cvsJoias;
     private CvsVendas cvsVendas;
     private Double cvsValorUnidade;
     private int cvsQuant;

    public CvsVendasjoias() {
    }

	
    public CvsVendasjoias(int cvsIdVendasJoias) {
        this.cvsIdVendasJoias = cvsIdVendasJoias;
    }
    public CvsVendasjoias(int cvsIdVendasJoias, CvsJoias cvsJoias, CvsVendas cvsVendas, Double cvsValorUnidade, int cvsQuant) {
       this.cvsIdVendasJoias = cvsIdVendasJoias;
       this.cvsJoias = cvsJoias;
       this.cvsVendas = cvsVendas;
       this.cvsValorUnidade = cvsValorUnidade;
       this.cvsQuant = cvsQuant;
    }
   
     @Id 

    
    @Column(name="cvs_idVendasJoias", unique=true, nullable=false)
    public int getCvsIdVendasJoias() {
        return this.cvsIdVendasJoias;
    }
    
    public void setCvsIdVendasJoias(int cvsIdVendasJoias) {
        this.cvsIdVendasJoias = cvsIdVendasJoias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cvs_id_codigo")
    public CvsJoias getCvsJoias() {
        return this.cvsJoias;
    }
    
    public void setCvsJoias(CvsJoias cvsJoias) {
        this.cvsJoias = cvsJoias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cvs_idVendas")
    public CvsVendas getCvsVendas() {
        return this.cvsVendas;
    }
    
    public void setCvsVendas(CvsVendas cvsVendas) {
        this.cvsVendas = cvsVendas;
    }

    
    @Column(name="cvs_valorUnidade", precision=10)
    public Double getCvsValorUnidade() {
        return this.cvsValorUnidade;
    }
    
    public void setCvsValorUnidade(Double cvsValorUnidade) {
        this.cvsValorUnidade = cvsValorUnidade;
    }

    
    @Column(name="cvs_quant")
    public int getCvsQuant() {
        return this.cvsQuant;
    }
    
    public void setCvsQuant(int cvsQuant) {
        this.cvsQuant = cvsQuant;
    }




}


