package bean;
// Generated 07/10/2025 20:07:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CvsVendas generated by hbm2java
 */
@Entity
@Table(name="cvs_vendas"
    ,catalog="db_camilly_souza"
)
public class CvsVendas  implements java.io.Serializable {


     private int cvsIdVenda;
     private CvsClientes cvsClientes;
     private CvsFuncionarios cvsFuncionarios;
     private Date cvsDataVenda;
     private double cvsTotal;

    public CvsVendas() {
    }

	
    public CvsVendas(int cvsIdVenda) {
        this.cvsIdVenda = cvsIdVenda;
    }
    public CvsVendas(int cvsIdVenda, CvsClientes cvsClientes, CvsFuncionarios cvsFuncionarios, Date cvsDataVenda, double cvsTotal) {
       this.cvsIdVenda = cvsIdVenda;
       this.cvsClientes = cvsClientes;
       this.cvsFuncionarios = cvsFuncionarios;
       this.cvsDataVenda = cvsDataVenda;
       this.cvsTotal = cvsTotal;
    }
   
     @Id 

    
    @Column(name="cvs_idVenda", unique=true, nullable=false)
    public int getCvsIdVenda() {
        return this.cvsIdVenda;
    }
    
    public void setCvsIdVenda(int cvsIdVenda) {
        this.cvsIdVenda = cvsIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cvs_idCliente")
    public CvsClientes getCvsClientes() {
        return this.cvsClientes;
    }
    
    public void setCvsClientes(CvsClientes cvsClientes) {
        this.cvsClientes = cvsClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cvs_idFuncionario")
    public CvsFuncionarios getCvsFuncionarios() {
        return this.cvsFuncionarios;
    }
    
    public void setCvsFuncionarios(CvsFuncionarios cvsFuncionarios) {
        this.cvsFuncionarios = cvsFuncionarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cvs_dataVenda", length=10)
    public Date getCvsDataVenda() {
        return this.cvsDataVenda;
    }
    
    public void setCvsDataVenda(Date cvsDataVenda) {
        this.cvsDataVenda = cvsDataVenda;
    }

    
    @Column(name="cvs_total", precision=10)
    public double getCvsTotal() {
        return this.cvsTotal;
    }
    
    public void setCvsTotal(double cvsTotal) {
        this.cvsTotal = cvsTotal;
    }






}


